#pragma once
#include "common.h"
#include "RGE_Animated_Object.h"

class RGE_Master_Doppleganger_Object;

class RGE_Doppleganger_Object : public RGE_Animated_Object {
public:
    RGE_Doppleganger_Object();
    RGE_Doppleganger_Object(int param_1, RGE_Game_World* param_2, int param_3);
    RGE_Doppleganger_Object(RGE_Master_Doppleganger_Object* param_1, RGE_Player* param_2, float param_3, float param_4, float param_5, int param_6, RGE_Static_Object* param_7);

    // Virtuals (best-effort)
    virtual ~RGE_Doppleganger_Object(); // vt[0] (0x0)
    virtual void recycle_in_to_game(RGE_Master_Static_Object* param_1, RGE_Player* param_2, float param_3, float param_4, float param_5); // vt[1] (0x4)
    virtual void recycle_out_of_game(); // vt[2] (0x8)
    virtual void draw(TDrawArea* param_1, short param_2, short param_3, RGE_Color_Table* param_4); // vt[3] (0xC)
    virtual void shadow_draw(TDrawArea* param_1, short param_2, short param_3, uchar param_4); // vt[4] (0x10)
    virtual void normal_draw(TDrawArea* param_1, short param_2, short param_3); // vt[5] (0x14)
    virtual void draw_front_frame(TDrawArea* param_1, short param_2, short param_3); // vt[6] (0x18)
    virtual void draw_back_frame(TDrawArea* param_1, short param_2, short param_3); // vt[7] (0x1C)
    virtual void draw_frame(TDrawArea* param_1, short param_2, short param_3); // vt[8] (0x20)
    virtual uchar update(); // vt[9] (0x24)
    virtual void check_damage_sprites(); // vt[10] (0x28)
    virtual void rehook(); // vt[11] (0x2C)
    virtual void save(int param_1); // vt[12] (0x30)
    virtual float teleport(float param_1, float param_2, float param_3); // vt[13] (0x34)
    virtual void new_sprite(RGE_Sprite* param_1); // vt[14] (0x38)
    virtual void add_overlay_sprite(RGE_Sprite* param_1, uchar param_2); // vt[15] (0x3C)
    virtual void remove_overlay_sprite(RGE_Sprite* param_1); // vt[16] (0x40)
    virtual void change_ownership(RGE_Player* param_1); // vt[17] (0x44)
    virtual void modify(float param_1, uchar param_2); // vt[18] (0x48)
    virtual void modify_delta(float param_1, uchar param_2); // vt[19] (0x4C)
    virtual void modify_percent(float param_1, uchar param_2); // vt[20] (0x50)
    virtual void transform(RGE_Master_Static_Object* param_1); // vt[21] (0x54)
    virtual void copy_obj(RGE_Master_Static_Object* param_1); // vt[22] (0x58)
    virtual void set_object_state(uchar param_1); // vt[23] (0x5C)
    virtual void remove_visible_resource(); // vt[24] (0x60)
    virtual void create_doppleganger_when_dying(); // vt[25] (0x64)
    virtual void destroy_obj(); // vt[26] (0x68)
    virtual void die_die_die(); // vt[27] (0x6C)
    virtual void damage(int param_1, RGE_Armor_Weapon_Info* param_2, float param_3, RGE_Player* param_4, RGE_Static_Object* param_5); // vt[28] (0x70)
    virtual float calculateDamage(int param_1, RGE_Armor_Weapon_Info* param_2, float param_3, RGE_Player* param_4, RGE_Static_Object* param_5); // vt[29] (0x74)
    virtual void rotate(long param_1); // vt[30] (0x78)
    virtual uchar can_attack(); // vt[31] (0x7C)
    virtual void set_attribute(short param_1, float param_2); // vt[32] (0x80)
    virtual void set_attribute_amount(float param_1, uchar param_2, uchar param_3); // vt[33] (0x84)
    virtual int heal(int param_1, int param_2); // vt[34] (0x88)
    virtual uchar heal(float param_1); // vt[35] (0x8C)
    virtual int canRepair(); // vt[36] (0x90)
    virtual void notify_of_relation(long param_1, uchar param_2); // vt[37] (0x94)
    virtual void do_command(RGE_Static_Object* param_1, float param_2, float param_3, float param_4); // vt[38] (0x98)
    virtual void move_to(RGE_Static_Object* param_1, float param_2, float param_3, float param_4); // vt[39] (0x9C)
    virtual void work(RGE_Static_Object* param_1, float param_2, float param_3, float param_4); // vt[40] (0xA0)
    virtual void stop(); // vt[41] (0xA4)
    virtual void set_attack(RGE_Static_Object* param_1); // vt[42] (0xA8)
    virtual void play_command_sound(); // vt[43] (0xAC)
    virtual void play_move_sound(); // vt[44] (0xB0)
    virtual void new_angle(float param_1); // vt[45] (0xB4)
    virtual RGE_Static_Object* spawn_death_obj(); // vt[46] (0xB8)
    virtual RGE_Master_Static_Object* get_command_master(RGE_Static_Object* param_1, float param_2, float param_3, float param_4); // vt[47] (0xBC)
    virtual void set_being_worked_on(RGE_Action_Object* param_1, short param_2, uchar param_3); // vt[48] (0xC0)
    virtual void release_being_worked_on(RGE_Static_Object* param_1); // vt[49] (0xC4)
    virtual uchar is_moving(); // vt[50] (0xC8)
    virtual RGE_Static_Object* get_target_obj(); // vt[51] (0xCC)
    virtual void enter_obj(RGE_Static_Object* param_1); // vt[52] (0xD0)
    virtual void exit_obj(); // vt[53] (0xD4)
    virtual int explore_terrain(RGE_Player* param_1, uchar param_2, int param_3); // vt[54] (0xD8)
    virtual void unexplore_terrain(RGE_Player* param_1, uchar param_2, int param_3); // vt[55] (0xDC)
    virtual LOSTBL* get_los_table(); // vt[56] (0xE0)
    virtual int inAttackRange(RGE_Static_Object* param_1); // vt[57] (0xE4)
    virtual uchar underAttack(); // vt[58] (0xE8)
    virtual void setUnderAttack(uchar param_1); // vt[59] (0xEC)
    virtual float calc_attack_modifier(RGE_Static_Object* param_1); // vt[60] (0xF0)
    virtual float getSpeed(); // vt[61] (0xF4)
    virtual float getAngle(); // vt[62] (0xF8)
    virtual float maximumSpeed(); // vt[63] (0xFC)
    virtual float rateOfFire(); // vt[64] (0x100)
    virtual float damageCapability(RGE_Static_Object* param_1); // vt[65] (0x104)
    virtual float damageCapability(); // vt[66] (0x108)
    virtual float weaponRange(); // vt[67] (0x10C)
    virtual float minimumWeaponRange(); // vt[68] (0x110)
    virtual int passableTile(float param_1, float param_2, int param_3); // vt[69] (0x114)
    virtual uchar facetToNextWaypoint(); // vt[70] (0x118)
    virtual int currentTargetID(); // vt[71] (0x11C)
    virtual float currentTargetX(); // vt[72] (0x120)
    virtual float currentTargetY(); // vt[73] (0x124)
    virtual float currentTargetZ(); // vt[74] (0x128)
    virtual void setWaitingToMove(uchar param_1); // vt[75] (0x12C)
    virtual uchar waitingToMove(); // vt[76] (0x130)
    virtual uchar actionState(); // vt[77] (0x134)
    virtual uchar keepGatheringWhenObjectIsOut(int param_1); // vt[78] (0x138)
    virtual uchar produceWhenKilledBy(int param_1); // vt[79] (0x13C)
    virtual uchar useSameZoneDropsite(); // vt[80] (0x140)
    virtual void logDebug(const char* param_1, ...); // vt[81] (0x144)
    virtual void notify(int param_1, int param_2, int param_3, long param_4, long param_5, long param_6); // vt[82] (0x148)
    virtual int attack(float param_1, float param_2, float param_3, int param_4); // vt[83] (0x14C)
    virtual int attack(int param_1, int param_2); // vt[84] (0x150)
    virtual int moveTo(float param_1, float param_2, float param_3, float param_4, int param_5); // vt[85] (0x154)
    virtual int moveTo(int param_1, float param_2, int param_3); // vt[86] (0x158)
    virtual int moveTo(int param_1, int param_2); // vt[87] (0x15C)
    virtual int moveAwayFrom(int param_1, int param_2); // vt[88] (0x160)
    virtual int hunt(int param_1, int param_2); // vt[89] (0x164)
    virtual int gather(int param_1, int param_2); // vt[90] (0x168)
    virtual int convert(int param_1, int param_2); // vt[91] (0x16C)
    virtual int repair(int param_1, int param_2); // vt[92] (0x170)
    virtual int build(int param_1, int param_2); // vt[93] (0x174)
    virtual int trade(int param_1, int param_2); // vt[94] (0x178)
    virtual int explore(int param_1, int param_2, int param_3); // vt[95] (0x17C)
    virtual int enter(int param_1, int param_2); // vt[96] (0x180)
    virtual int unload(int param_1, float param_2, float param_3, float param_4); // vt[97] (0x184)
    virtual int transport(float param_1, float param_2, float param_3, int param_4); // vt[98] (0x188)
    virtual int stopAction(); // vt[99] (0x18C)
    virtual int pause(); // vt[100] (0x190)
    virtual int canPath(int param_1, float param_2, float* param_3, int param_4, int param_5, int param_6); // vt[101] (0x194)
    virtual int canPath(XYZPoint param_1, float param_2, int param_3, float* param_4, int param_5, int param_6, int param_7); // vt[102] (0x198)
    virtual int canBidirectionPath(int param_1, int param_2, float param_3, float* param_4, int param_5, int param_6, int param_7); // vt[103] (0x19C)
    virtual int canPathWithObstructions(int param_1, float param_2, float* param_3, int param_4, int param_5, int param_6, ManagedArray<int>* param_7); // vt[104] (0x1A0)
    virtual int canPathWithAdditionalPassability(XYZPoint param_1, float param_2, int param_3, float* param_4, int param_5, int param_6, int param_7, int param_8, int param_9); // vt[105] (0x1A4)
    virtual int findFirstTerrainAlongExceptionPath(int param_1, float* param_2, float* param_3); // vt[106] (0x1A8)
    virtual int canLinePath(int param_1, int param_2, int param_3, int param_4, float param_5, int param_6); // vt[107] (0x1AC)
    virtual int canLinePath(XYPoint* param_1, XYPoint* param_2, float param_3, XYPoint* param_4, int param_5); // vt[108] (0x1B0)
    virtual int firstTileAlongLine(XYPoint* param_1, XYPoint* param_2, XYPoint* param_3, int param_4, int param_5, int param_6); // vt[109] (0x1B4)
    virtual XYZBYTEPoint* userDefinedWaypoint(int param_1); // vt[110] (0x1B8)
    virtual int addUserDefinedWaypoint(XYZBYTEPoint* param_1, int param_2); // vt[111] (0x1BC)
    virtual void removeAllUserDefinedWaypoints(int param_1); // vt[112] (0x1C0)
    virtual void removeUserDefinedWaypoint(int param_1); // vt[113] (0x1C4)
    virtual int numberUserDefinedWaypoints(); // vt[114] (0x1C8)
    virtual Path* findAvoidancePath(XYZPoint* param_1, float param_2, int param_3); // vt[115] (0x1CC)
    virtual long get_action_checksum(); // vt[116] (0x1D0)
    virtual long get_waypoint_checksum(); // vt[117] (0x1D4)
    virtual int setup(int param_1, RGE_Game_World* param_2); // vt[118] (0x1D8)
    virtual int setup(RGE_Master_Static_Object* param_1, RGE_Player* param_2, float param_3, float param_4, float param_5); // vt[119] (0x1DC)
    virtual RGE_Object_List* create_object_list(); // vt[120] (0x1E0)
    virtual RGE_Active_Sprite_List* create_sprite_list(); // vt[121] (0x1E4)
    virtual int setup(RGE_Master_Animated_Object* param_1, RGE_Player* param_2, float param_3, float param_4, float param_5); // vt[122] (0x1E8)
    virtual void recycle_in_to_game(RGE_Master_Static_Object* param_1, RGE_Player* param_2, float param_3, float param_4, float param_5, RGE_Static_Object* param_6); // vt[123] (0x1EC)
    virtual void validate(); // vt[124] (0x1F0)
    virtual int setup(RGE_Master_Doppleganger_Object* param_1, RGE_Player* param_2, float param_3, float param_4, float param_5); // vt[125] (0x1F4)

    RGE_Static_Object* doppled_object;
    RGE_Color_Table* draw_color;
    RGE_Master_Static_Object* doppled_master_obj;
    int doppled_player;
    unsigned long* MapAddress;
    unsigned long LastMapValue;
    unsigned long CantSeeBits;
    unsigned char map_draw_level;
    unsigned char map_color;
    int doppledObjectID;
};
static_assert(sizeof(RGE_Doppleganger_Object) == 0xB0, "Size mismatch");
