#pragma once
#include "common.h"

struct TMusic_System {
    char path[260];
    uchar music_type;
    TSound_Driver* sound_system;
    void* instance;
    void* window;
    int device_open;
    uint device_id;
    tagMCI_PLAY_PARMS play_info;
    uchar playing_track;
    char file_name[261];
    int start_track;
    int end_track;
    int make_cur_track;
    ulong set_pos;
    int loop;
    int current_track;
    int track_count;
    int notify_waiting;
    long start_volume;
    long volume;
    int paused;
    int auto_paused;
    int inactivated;
    int fade_out;
    ulong fade_time;
    int fading_track;
    long fade_volume;
    ulong last_fade_time;
    int mixer_open;
    void* mixer_handle;
    tagMIXERLINEA mixer_line_info;
    tagMIXERLINECONTROLSA mixer_line_controls;
    tagMIXERCONTROLA mixer_volume_control;
    tMIXERCONTROLDETAILS mixer_volume_details;
    tMIXERCONTROLDETAILS_UNSIGNED mixer_volume_value;
    void* midi_window;
    ulong last_check_time;

    TMusic_System(uchar music_type, void* instance, void* window, TSound_Driver* sound_system, char* path);
    ~TMusic_System();
    int open_device();
    void close_device();
    int open_mixer();
    void close_mixer();
    int set_music_type(uchar type);
    void set_fade_out(int fade_out, ulong fade_time);
    void set_volume(long vol, int save);
    int play_track(int track, int loop, ulong set_pos);
    int play_file(char* filename, int loop, ulong set_pos);
    int play_tracks(int start_track, int end_track, int loop, int make_cur_track, ulong set_pos);
    int play(int start_track, int end_track, char* filename, int loop, ulong set_pos);
    int pause_play();
    int resume_play();
    int stop_track();
    int stop_playing();
    int fade_track();
    void start_fade();
    void do_fade();
    void end_fade();
    uint handle_messages(void* hwnd, uint msg, uint wParam, long lParam);
    void after_end_track();
    int get_play_info(uchar* playing, int* track, int* start, int* end, char* filename, int* looping, ulong* pos);
};
static_assert(sizeof(TMusic_System) == 0x3F8, "Size mismatch");
