#pragma once

#include "TScreenPanel.h"

class TRIBE_World;
class TTextPanel;
class TMessagePanel;
class RGE_Panel_Tool_Box;
class TScrollBarPanel;
class TRIBE_Panel_Inven;
class TRIBE_Panel_Object;
class TRIBE_Panel_Time;
class TRIBE_Panel_Pop;
class TRIBE_Panel_Button;
struct TDigital;
class TShape;
struct Item_Avail;

class TRIBE_Screen_Game : public TScreenPanel {
public:
    TRIBE_Screen_Game();
    virtual ~TRIBE_Screen_Game();

    void handle_game_update();
    void game_mode_changed(int new_mode, int old_mode);
    void player_changed(int old_player, int new_player);
    void handle_pause();
    void handle_resume();
    void handleChatReceived(int from_player);
    void display_system_message(char* text);
    void setup_buttons();
    void reset_clocks();
    void reset_buttons();
    void command_score(int enabled);
    void reset_score_display();
    void show_timings(char* param_1, char* param_2);
    void show_comm(char* param_1, char* param_2, char* param_3, char* param_4, char* param_5, char* param_6);
    void show_ai(char* param_1, char* param_2, char* param_3, char* param_4, char* param_5, char* param_6);
    void show_message(int type, char* text, unsigned char color1, unsigned char color2);
    void disable_unused_buttons();
    void add_log(char* text);
    void set_map_buttons_redraw(RedrawMode param_1);
    virtual void draw() override;
    virtual void set_redraw(RedrawMode param_1) override;
    virtual void set_overlapped_redraw(TPanel* param_1, TPanel* param_2, RedrawMode param_3) override;
    virtual long wnd_proc(void* param_1, uint param_2, uint param_3, long param_4) override;
    virtual long handle_idle() override;
    virtual long handle_size(long param_1, long param_2) override;
    virtual long handle_paint() override;
    virtual long handle_mouse_down(uchar param_1, long param_2, long param_3, int param_4, int param_5) override;
    virtual long key_down_action(long param_1, short param_2, int param_3, int param_4, int param_5) override;
    virtual long char_action(long param_1, short param_2) override;
    virtual long action(TPanel* param_1, long param_2, ulong param_3, ulong param_4) override;
    virtual long handle_user_command(uint param_1, long param_2) override;
    virtual void set_focus(int param_1) override;
    virtual void stop_sound_system() override;
    virtual int restart_sound_system() override;

protected:
    void do_button_action(int param_1, int param_2, int param_3);
    char* calc_text_msg(char* param_1, Item_Avail* param_2, long param_3, long param_4);
    short calc_button_loc(unsigned char param_1);
    void set_button(TShape* param_1, short param_2, short param_3, long param_4, long param_5, long param_6, long param_7, long param_8, unsigned char* param_9, char* param_10, char* param_11, int param_12);
    void handle_anim_pal();
    void handle_terrain_sound();
    void handle_mouse_pointing_at();
    void command_add_attribute(int param_1);
    void command_ai_info();
    void command_attack();
    void command_build();
    void command_building(int param_1);
    void command_cancel();
    void command_cancel_building();
    void command_chat();
    void command_quick_chat();
    void command_comm_info();
    void command_convert();
    void command_diplomacy();
    void command_fog_of_war();
    void command_fps();
    void command_game_speed(int param_1);
    void command_group();
    void command_group_by_number(int param_1);
    void command_heal();
    void command_repair();
    void command_select_group(int param_1, int param_2);
    void command_menu();
    void command_more();
    void command_move();
    void command_outline();
    void command_pause();
    void command_player(int param_1);
    void command_quick_build();
    void command_quit();
    void command_research(int param_1);
    void command_save_game();
    void command_save_scenario();
    void command_select_building(int param_1);
    void command_stop();
    void command_tool_box();
    void command_trade();
    void command_trade_with(int param_1);
    void command_train(int param_1, short param_2);
    void command_ungroup();
    void command_unload();
    void command_unselect();
    void command_view_selected();
    void command_view_tribe();
    void command_visibility();
    void command_work();
    void command_formation(int param_1);
    void command_stand_ground();
    void command_attack_ground();
    void command_trade_attribute(long param_1);
    void command_tab_selected(int param_1);
    int any_selected_have_action();
    void object_changed();
    void age_changed();

private:
    struct RuntimeState {
        TShape* game_screen_pic;
        TShape* button_border1_pic;
        TShape* button_other_pic;
        TShape* button_border2_pic;
        TShape* button_border3_pic;
        TShape* button_cmd_pic;
        TShape* button_tech_pic;
        TShape* button_unit_pic;
        TShape* button_bldg_pics[5];
        TShape* more_cancel_pic;

        TRIBE_World* world;
        TPanel* main_view;
        TPanel* map_view;
        TTextPanel* pause_text;
        TTextPanel* age_panel;
        TTextPanel* fps_panel;
        TMessagePanel* score_panel[8];
        TTextPanel* log_text;
        TScrollBarPanel* log_scrollbar;
        TMessagePanel* text_line_panel;
        TTextPanel* quit_message_panel;
        TMessagePanel* message_panel[6];
        TMessagePanel* chat_panel[8];
        TRIBE_Panel_Inven* inven_panel;
        TRIBE_Panel_Object* object_panel;
        TRIBE_Panel_Time* time_panel;
        TRIBE_Panel_Time* countdown_clock[10];
        TRIBE_Panel_Pop* pop_panel;
        TRIBE_Panel_Button* button_panel[17];
        RGE_Panel_Tool_Box* tool_box;
        void* tech_list;
        void* make_list;
        void* bldg_list;
        void* trade_list;
        TDigital* game_over_sound;
        RGE_Static_Object* last_selected_obj;
        short last_sel_count;
        short selection_pad;
        short start_item;
        short current_item;
        int chat_line;
        short last_item;
        short reserved;
        unsigned long terrain_sound_interval;
        unsigned long last_terrain_sound_time;
        unsigned long anim_pal_interval;
        unsigned long last_anim_pal_time;
        short last_anim_pal_index2;
        short last_anim_pal_index3;
        unsigned char last_score_display;
        unsigned char score_padding[3];
        unsigned long update_interval;
        unsigned long last_update_time;
        unsigned long map_redraw_interval;
        unsigned long last_map_redraw_time;
        int save_age;
        unsigned long score_interval;
        unsigned long last_score_time;
        unsigned long view_interval;
        unsigned long last_view_time;
        int reset_after_update;
        int watch_mode;
    };

    static const int kScreenSize = 0x7C4;
    RuntimeState runtime;
    unsigned char shim_padding[kScreenSize - sizeof(TScreenPanel) - sizeof(RuntimeState)];
};

static_assert(sizeof(TScreenPanel) <= 0x7C4, "TScreenPanel exceeds TRIBE_Screen_Game size");
static_assert(sizeof(TRIBE_Screen_Game) == 0x7C4, "Size mismatch");
