#pragma once
#include "common.h"
#include "UnitAIModule.h"

class TribeElephantUnitAIModule : public UnitAIModule {
public:
    TribeElephantUnitAIModule(RGE_Static_Object* param_1, int param_2);
    // Virtuals (best-effort)
    virtual ~TribeElephantUnitAIModule(); // vt[0] (0x0)
    virtual void save(int param_1); // vt[1] (0x4)
    virtual void load(int param_1); // vt[2] (0x8)
    virtual RGE_Player* owner(); // vt[3] (0xC)
    virtual int order(int param_1, int param_2, int param_3, int param_4, float param_5, float param_6, float param_7, float param_8, int param_9, int param_10, int param_11); // vt[4] (0x10)
    virtual int notify(int param_1, int param_2, int param_3, long param_4, long param_5, long param_6); // vt[5] (0x14)
    virtual int notifyCommander(int param_1, int param_2, int param_3, long param_4, long param_5, long param_6); // vt[6] (0x18)
    virtual int notifyCommander(NotifyEvent* param_1); // vt[7] (0x1C)
    virtual void search(); // vt[8] (0x20)
    virtual int importantWhenDead(int param_1); // vt[9] (0x24)
    virtual int retryableOrder(int param_1); // vt[10] (0x28)
    virtual int actionRequiresLiveTarget(int param_1); // vt[11] (0x2C)
    virtual int bestUnitToAttack(int param_1, int param_2, float* param_3); // vt[12] (0x30)
    virtual int mostDangerousEnemy(float* param_1); // vt[13] (0x34)
    virtual int weakestEnemy(float* param_1); // vt[14] (0x38)
    virtual int closestAttacker(float* param_1); // vt[15] (0x3C)
    virtual int closestObject(int param_1, int param_2, int param_3, int param_4, int* param_5); // vt[16] (0x40)
    virtual int closestResourceObject(int param_1, int* param_2); // vt[17] (0x44)
    virtual int closestUndiscoveredTile(int* param_1, int* param_2, int param_3); // vt[18] (0x48)
    virtual void logDebug(char* param_1); // vt[19] (0x4C)
    virtual int canAttackUnit(RGE_Static_Object* param_1); // vt[20] (0x50)
    virtual int canAttackUnitAtNeutrality(int param_1); // vt[21] (0x54)
    virtual int stopObject(int param_1); // vt[22] (0x58)
    virtual int attackObject(int param_1, int param_2); // vt[23] (0x5C)
    virtual int attackRoundupObject(int param_1); // vt[24] (0x60)
    virtual int huntObject(int param_1, int param_2); // vt[25] (0x64)
    virtual int gatherObject(int param_1, int param_2); // vt[26] (0x68)
    virtual int convertObject(int param_1, int param_2); // vt[27] (0x6C)
    virtual int healObject(int param_1, int param_2); // vt[28] (0x70)
    virtual int repairObject(int param_1, int param_2); // vt[29] (0x74)
    virtual int buildObject(int param_1, int param_2); // vt[30] (0x78)
    virtual int tradeWithObject(int param_1, int param_2); // vt[31] (0x7C)
    virtual int explore(int param_1, int param_2, int param_3); // vt[32] (0x80)
    virtual int enterObject(int param_1, int param_2); // vt[33] (0x84)
    virtual int unload(int param_1, float param_2, float param_3); // vt[34] (0x88)
    virtual int transportObject(float param_1, float param_2, float param_3, int param_4); // vt[35] (0x8C)
    virtual int moveTo(float param_1, float param_2, float param_3, float param_4, int param_5); // vt[36] (0x90)
    virtual int moveTo(int param_1, float param_2, int param_3); // vt[37] (0x94)
    virtual int moveTo(int param_1, int param_2); // vt[38] (0x98)
    virtual int evasiveMoveTo(float param_1, float param_2, float param_3, int param_4); // vt[39] (0x9C)
    virtual int intelligentEvasiveMoveTo(float param_1, float param_2, float param_3, int param_4, int param_5); // vt[40] (0xA0)
    virtual int runAwayFromAttackers(int param_1); // vt[41] (0xA4)
    virtual int followObject(int param_1, float param_2, int param_3); // vt[42] (0xA8)
    virtual int defendObject(int param_1, float param_2, int param_3); // vt[43] (0xAC)
    virtual int defendPosition(float param_1, float param_2, float param_3, int param_4); // vt[44] (0xB0)
    virtual int seekAndDestroy(int param_1, int param_2, int param_3, int param_4); // vt[45] (0xB4)
    virtual int exploreAndDestroy(int param_1, int param_2, int param_3); // vt[46] (0xB8)
    virtual int importantObject(int param_1); // vt[47] (0xBC)
    virtual int convertToLOSResourceType(int param_1); // vt[48] (0xC0)
    virtual int canConvert(int param_1); // vt[49] (0xC4)
    virtual int processOrder(OrderEvent* param_1, int param_2); // vt[50] (0xC8)
    virtual int processNotify(NotifyEvent* param_1, ulong param_2); // vt[51] (0xCC)
    virtual void processGroupNotify(NotifyEvent* param_1); // vt[52] (0xD0)
    virtual int processIdle(int param_1); // vt[53] (0xD4)
    virtual int processMisc(); // vt[54] (0xD8)
    virtual int processRetryableOrder(); // vt[55] (0xDC)

};
static_assert(sizeof(TribeElephantUnitAIModule) == 0x134, "Size mismatch");
