#pragma once
#include "common.h"
#include "TRIBE_Player.h"

class TRIBE_Gaia : public TRIBE_Player {
public:
    // Virtuals (best-effort)
    virtual ~TRIBE_Gaia(); // vt[0] (0x0)
    virtual void set_game_status(uchar param_1); // vt[1] (0x4)
    virtual void do_resign(int param_1); // vt[2] (0x8)
    virtual void changeToHumanPlayer(); // vt[3] (0xC)
    virtual void changeToComputerPlayer(); // vt[4] (0x10)
    virtual char* aiStatus(int param_1); // vt[5] (0x14)
    virtual int isEnemy(int param_1); // vt[6] (0x18)
    virtual int isAlly(int param_1); // vt[7] (0x1C)
    virtual int isNeutral(int param_1); // vt[8] (0x20)
    virtual int isAllNeutral(); // vt[9] (0x24)
    virtual void setDiplomaticStance(int param_1, int param_2); // vt[10] (0x28)
    virtual void loadAIInformation(char* param_1, char* param_2, char* param_3, int param_4, int param_5); // vt[11] (0x2C)
    virtual void sendUnitAIOrder(int param_1, int param_2, int param_3, int param_4, int param_5, float param_6, float param_7, float param_8, float param_9, int param_10, int param_11, int param_12); // vt[12] (0x30)
    virtual void processAIOrder(int param_1, int param_2, int param_3, int param_4, int param_5, float param_6, float param_7, float param_8, float param_9, int param_10, int param_11, int param_12); // vt[13] (0x34)
    virtual void kickAI(int param_1); // vt[14] (0x38)
    virtual int strategicNumber(int param_1); // vt[15] (0x3C)
    virtual void sendGameOrder(RGE_Static_Object* param_1, RGE_Static_Object* param_2, float param_3, float param_4); // vt[16] (0x40)
    virtual void sendAddWaypointCommand(int param_1, XYZBYTEPoint* param_2, int param_3); // vt[17] (0x44)
    virtual void processAddWaypointCommand(int param_1, XYZBYTEPoint* param_2, int param_3); // vt[18] (0x48)
    virtual void sendPlayCommand(int param_1, int* param_2, int param_3, int param_4, int param_5); // vt[19] (0x4C)
    virtual void sendPlayCommand(int param_1, int param_2, int param_3); // vt[20] (0x50)
    virtual int sendAICommand(int param_1, int param_2, int param_3, int param_4, int param_5); // vt[21] (0x54)
    virtual int objectCostByType(int param_1); // vt[22] (0x58)
    virtual void trackUnitGather(int param_1, int param_2, int param_3); // vt[23] (0x5C)
    virtual RGE_Static_Object* make_scenario_obj(float param_1, float param_2, float param_3, short param_4, uchar param_5, float param_6); // vt[24] (0x60)
    virtual void scenario_save(int param_1); // vt[25] (0x64)
    virtual void scenario_load(int param_1, long* param_2, float param_3); // vt[26] (0x68)
    virtual void scenario_postsave(int param_1); // vt[27] (0x6C)
    virtual void scenario_postload(int param_1, long* param_2, float param_3); // vt[28] (0x70)
    virtual void load(int param_1); // vt[29] (0x74)
    virtual void add_attribute_num(short param_1, float param_2, uchar param_3); // vt[30] (0x78)
    virtual void update(); // vt[31] (0x7C)
    virtual void update_dopplegangers(); // vt[32] (0x80)
    virtual void save(int param_1); // vt[33] (0x84)
    virtual void save2(int param_1); // vt[34] (0x88)
    virtual void save_info(int param_1); // vt[35] (0x8C)
    virtual void random_start(); // vt[36] (0x90)
    virtual RGE_Static_Object* make_new_object(long param_1, float param_2, float param_3, float param_4, int param_5); // vt[37] (0x94)
    virtual void analyize_selected_objects(); // vt[38] (0x98)
    virtual int get_mouse_pointer_action_vars(int param_1, int* param_2, int* param_3); // vt[39] (0x9C)
    virtual uchar command_make_move(RGE_Static_Object* param_1, float param_2, float param_3); // vt[40] (0xA0)
    virtual uchar command_make_work(RGE_Static_Object* param_1, float param_2, float param_3); // vt[41] (0xA4)
    virtual uchar command_make_do(RGE_Static_Object* param_1, float param_2, float param_3); // vt[42] (0xA8)
    virtual uchar command_stop(); // vt[43] (0xAC)
    virtual uchar command_place_object(short param_1, float param_2, float param_3, float param_4); // vt[44] (0xB0)
    virtual uchar command_add_attribute(int param_1, float param_2); // vt[45] (0xB4)
    virtual uchar command_give_attribute(int param_1, int param_2, float param_3); // vt[46] (0xB8)
    virtual uchar command_formation(int param_1); // vt[47] (0xBC)
    virtual uchar command_stand_ground(); // vt[48] (0xC0)
    virtual uchar command_create_group(int param_1, int* param_2, int param_3, float param_4); // vt[49] (0xC4)
    virtual uchar command_add_to_group(int param_1, int param_2, float param_3); // vt[50] (0xC8)
    virtual uchar command_remove_from_group(int param_1, int param_2); // vt[51] (0xCC)
    virtual uchar command_destroy_group(int param_1); // vt[52] (0xD0)
    virtual uchar command_resign(int param_1, int param_2); // vt[53] (0xD4)
    virtual uchar command_add_waypoint(float param_1, float param_2, float param_3); // vt[54] (0xD8)
    virtual RGE_Object_Node* addObject(RGE_Static_Object* param_1, int param_2, int param_3); // vt[55] (0xDC)
    virtual void removeObject(RGE_Static_Object* param_1, int param_2, int param_3, RGE_Object_Node* param_4); // vt[56] (0xE0)
    virtual void logMessage(char* param_1); // vt[57] (0xE4)
    virtual void notify(int param_1, int param_2, int param_3, long param_4, long param_5, long param_6); // vt[58] (0xE8)
    virtual void logStatus(FILE* param_1, int param_2); // vt[59] (0xEC)
    virtual void load_victory(int param_1, long* param_2, uchar param_3); // vt[60] (0xF0)
    virtual void new_victory(); // vt[61] (0xF4)
    virtual uchar command_give_attribute(int param_1, int param_2, float param_3, float param_4); // vt[62] (0xF8)
    virtual void buildObject(int param_1, int param_2, float param_3, float param_4, int param_5); // vt[63] (0xFC)
    virtual void cancelBuild(int param_1, int param_2, int param_3, float param_4, float param_5, int param_6, int param_7); // vt[64] (0x100)
    virtual void registerBuild(RGE_Static_Object* param_1, int param_2); // vt[65] (0x104)
    virtual void trainUnit(int param_1, int param_2, int param_3); // vt[66] (0x108)
    virtual void cancelTrain(int param_1, int param_2, int param_3, int param_4); // vt[67] (0x10C)
    virtual void registerTrain(int param_1, int param_2, int param_3, int param_4); // vt[68] (0x110)
    virtual void research(int param_1, int param_2, int param_3); // vt[69] (0x114)
    virtual void cancelResearch(int param_1, int param_2, int param_3, int param_4); // vt[70] (0x118)
    virtual void registerResearch(int param_1, int param_2, int param_3); // vt[71] (0x11C)
    virtual void taskTrader(int param_1, int param_2, int param_3, float param_4, float param_5); // vt[72] (0x120)
    virtual void taskResourceGatherer(int param_1, int param_2, int param_3, float param_4, float param_5); // vt[73] (0x124)
    virtual void notifyAI(int param_1, int param_2, int param_3, long param_4, long param_5, long param_6); // vt[74] (0x128)

    float update_time;
    long update_nature;
    long last_count;
    long animal_max;
};
static_assert(sizeof(TRIBE_Gaia) == 0x858, "Size mismatch");
